
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="geode"
version="1.0.2"
displayName="Geode+"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geode-forge"
logoFile="logo.png"
authors="Owner: YeoXuHang, Artist: Heizer"
description='''
a mod that add geodes to Minecraft Overworld, Nether and even The End!
'''
[[dependencies.geode]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.geode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
